In [11]:
import os
import copy
import csv
import numpy as np
import pandas as pd
import brainbox.io.one as bbone
import ibllib.atlas as atlas
import pickle
from one.api import ONE
one = ONE(base_url='https://alyx.internationalbrainlab.org')

UUID_TO_INDEX_PATH = "./data/uuid_index.pkl"
MLAPDV_PATH = "./data/mlapdv_with_uuid.csv"
RF_DATA_PATH = "./data/ibl_rf_fits.csv"
EVENT_AVG_PATH = "./data/cluster_trail_event_avgs.pkl"

In [12]:
from brainbox.io.one import SpikeSortingLoader


In [13]:
eids = np.load("data/brainwide_map_eids_ephys_histology.npy")


In [14]:
# Load the UUID index file
with open(UUID_TO_INDEX_PATH, 'rb') as uuid_file:
  uuids = pickle.load(uuid_file)

In [15]:
sess_info = one.alyx.rest("sessions","list")
eid2lab = {}
for sess in sess_info:
    eid = one.to_eid(sess['url'])
    eid2lab[eid] = sess['lab']

In [16]:
# build a CSV file which tracks the UUID and lab that each cluster came from
with open('data/metadata.csv','w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  for uuid, index in uuids.items():
    eid = data['eid']
    writer.writerow([uuid, eid2lab[eid]])

TypeError: 'int' object is not subscriptable

In [136]:
from matplotlib import cm
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [20, 10]
import time

In [113]:
# Load all of the ISI_AMP csv files and populate a big matrix with the cluster count data
# then plot slices of this to look at the cluster count
isi_amp_dir = 'C:\proj\IBL\cluster_pipelines\data\isi_amp_data'

files = os.listdir(isi_amp_dir)

# 528*320*456  ap/dv/lr
cluCount = np.zeros((456,528,320))

for file in files:
    df = pd.read_csv('C:\proj\IBL\cluster_pipelines\data\isi_amp_data\\' + file)
    df.reset_index()
    for i,row in df.iterrows():
        cluCount[int(row['ml']/40),int(row['ap']/40),int(row['dv']/40)] = row['clu_count']

In [209]:
# New plan:
# Load each ISI_AMP file and save each leaf node area separately as a CSV
# Average the ISI distribution for that area (or do PCA on it?)

isi_amp_dir = 'C:\proj\IBL\cluster_pipelines\data\isi_amp_data'
files = os.listdir(isi_amp_dir)

df = pd.read_csv('C:\proj\IBL\cluster_pipelines\data\isi_amp_data\\' + files[0])
# dictionary containing area data
areaData = pd.DataFrame(columns=['area',df.columns[9:].values])
i = 0

for file in files:
    df = pd.read_csv('C:\proj\IBL\cluster_pipelines\data\isi_amp_data\\' + file)
    df.reset_index()
    for i,row in df.iterrows():
        area = row['atlas_id']
        data = row[9:].values
        areaData.loc[i] = [area, data]
        i += 1

AttributeError: 'numpy.float64' object has no attribute 'values'

In [203]:
for area in areaDict.keys():
    areaData = areaDict[area]
    areaMean = np.average(areaData,axis=0)
    #np.savetxt('C:\proj\IBL\cluster_pipelines\data\isi_amp_areas\\' + str(area) + '.csv',areaData,delimiter=',')

In [216]:
np.average(areaDict[0],axis=0)

array([0.02462212, 0.04363561, 0.10895899, 0.15841355, 0.15662258,
       0.15228122, 0.12637609, 0.10094896, 0.0703425 , 0.05779838])

In [213]:
areaMean = np.average(areaData,axis=0)


C:\Users\Dan\.conda\envs\iblenv\lib\site-packages\numpy\lib\function_base.py:495: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)


ZeroDivisionError: division by zero

In [210]:
area

512.0

In [211]:
data

array([5.78268664e-04, 1.34929355e-03, 8.23069065e-03, 9.80281039e-01,
       9.31012548e-03, 9.63781106e-05, 7.71024885e-05, 7.71024885e-05,
       0.00000000e+00, 0.00000000e+00])

In [212]:
[area,data]

[512.0,
 array([5.78268664e-04, 1.34929355e-03, 8.23069065e-03, 9.80281039e-01,
        9.31012548e-03, 9.63781106e-05, 7.71024885e-05, 7.71024885e-05,
        0.00000000e+00, 0.00000000e+00])]